// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type FlexiblePageDocumentDataSlicesSlice =
  | WysiwygTextBlockSlice
  | SubservicesSlice
  | FaqSlice
  | ContactInfoSlice
  | ServicesListsSlice
  | TeamListsSlice
  | TeamPartnersSlice
  | FeaturedListsSlice
  | StepsSlice
  | CtaSlice
  | FeaturedServicesSlice
  | QuoteSlice
  | AdvantageSlice
  | HeroSlice;

/**
 * Content for Flexible Page documents
 */
interface FlexiblePageDocumentData {
  /**
   * Slice Zone field in *Flexible Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: flexiblePage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<FlexiblePageDocumentDataSlicesSlice> /**
   * Meta Description field in *Flexible Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: flexiblePage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Flexible Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: flexiblePage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Flexible Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: flexiblePage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Flexible Page document from Prismic
 *
 * - **API ID**: `flexiblePage`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FlexiblePageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<FlexiblePageDocumentData>,
    "flexiblePage",
    Lang
  >;

/**
 * Item in *Global Sections → step items*
 */
export interface GlobalSectionsDocumentDataStepItemsItem {
  /**
   * heading field in *Global Sections → step items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: globalSections.stepItems[].heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * description field in *Global Sections → step items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: globalSections.stepItems[].description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;
}

/**
 * Content for Global Sections documents
 */
interface GlobalSectionsDocumentData {
  /**
   * heading field in *Global Sections*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: globalSections.footerHeading
   * - **Tab**: Footer
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  footerHeading: prismic.RichTextField /**
   * steps Heading field in *Global Sections*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: globalSections.stepsHeading
   * - **Tab**: Steps
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */;
  stepsHeading: prismic.RichTextField;

  /**
   * step items field in *Global Sections*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: globalSections.stepItems[]
   * - **Tab**: Steps
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  stepItems: prismic.GroupField<
    Simplify<GlobalSectionsDocumentDataStepItemsItem>
  > /**
   * cta preheading field in *Global Sections*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: globalSections.ctaPreheading
   * - **Tab**: Cta
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */;
  ctaPreheading: prismic.TitleField;

  /**
   * cta heading field in *Global Sections*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: globalSections.ctaHeading
   * - **Tab**: Cta
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  ctaHeading: prismic.TitleField;

  /**
   * cta body text field in *Global Sections*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: globalSections.ctaBodyText
   * - **Tab**: Cta
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  ctaBodyText: prismic.RichTextField;

  /**
   * cta button text field in *Global Sections*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: globalSections.ctaButtonText
   * - **Tab**: Cta
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  ctaButtonText: prismic.KeyTextField;

  /**
   * cta button link field in *Global Sections*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: globalSections.ctaButtonLink
   * - **Tab**: Cta
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  ctaButtonLink: prismic.LinkField /**
   * quote heading field in *Global Sections*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: globalSections.quoteHeading
   * - **Tab**: Quote
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */;
  quoteHeading: prismic.RichTextField;
}

/**
 * Global Sections document from Prismic
 *
 * - **API ID**: `globalSections`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type GlobalSectionsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<GlobalSectionsDocumentData>,
    "globalSections",
    Lang
  >;

type LandingPageDocumentDataSlicesSlice =
  | WysiwygTextBlockSlice
  | CtaContactSlice
  | SubservicesSlice
  | FaqSlice
  | AboutHeadingBodytextSlice
  | TeamPartnersSlice
  | CtaGuaranteeSlice
  | StepsSlice
  | AboutImageSlice
  | BenefitsSlice
  | LpHeroSlice;

/**
 * Content for Landing Page documents
 */
interface LandingPageDocumentData {
  /**
   * Slice Zone field in *Landing Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: landingPage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<LandingPageDocumentDataSlicesSlice> /**
   * Meta Description field in *Landing Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: landingPage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Landing Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: landingPage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Landing Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: landingPage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Landing Page document from Prismic
 *
 * - **API ID**: `landingPage`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LandingPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<LandingPageDocumentData>,
    "landingPage",
    Lang
  >;

type ServiceDocumentDataSlicesSlice =
  | FaqSlice
  | CtaSlice
  | AboutHeadingBodytextSlice
  | StepsSlice
  | SubservicesSlice
  | QuoteSlice
  | ServiceHeaderSlice;

/**
 * Content for Service documents
 */
interface ServiceDocumentData {
  /**
   * name field in *Service*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * featured description field in *Service*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service.featuredDescription
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  featuredDescription: prismic.RichTextField;

  /**
   * featured icon field in *Service*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: service.featuredIcon
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  featuredIcon: prismic.ImageField<never>;

  /**
   * Slice Zone field in *Service*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: service.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ServiceDocumentDataSlicesSlice> /**
   * Meta Description field in *Service*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: service.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Service*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: service.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Service*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: service.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Service document from Prismic
 *
 * - **API ID**: `service`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ServiceDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ServiceDocumentData>,
    "service",
    Lang
  >;

type SettingsDocumentDataSlicesSlice = NavigationItemSlice;

type SettingsDocumentDataSlices1Slice = FooterNavigationItemSlice;

/**
 * Item in *Settings → social*
 */
export interface SettingsDocumentDataSocialItem {
  /**
   * platform field in *Settings → social*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.social[].platform
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  platform: prismic.KeyTextField;

  /**
   * link field in *Settings → social*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.social[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Item in *Settings → images*
 */
export interface SettingsDocumentDataImagesItem {
  /**
   * image field in *Settings → images*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.images[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * Slice Zone field in *Settings*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.slices[]
   * - **Tab**: Header Menu
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<SettingsDocumentDataSlicesSlice> /**
   * Slice Zone field in *Settings*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.slices1[]
   * - **Tab**: Footer Menu
   * - **Documentation**: https://prismic.io/docs/field#slices
   */;
  slices1: prismic.SliceZone<SettingsDocumentDataSlices1Slice> /**
   * social field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.social[]
   * - **Tab**: Social
   * - **Documentation**: https://prismic.io/docs/field#group
   */;
  social: prismic.GroupField<Simplify<SettingsDocumentDataSocialItem>> /**
   * logo field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.logo
   * - **Tab**: seo
   * - **Documentation**: https://prismic.io/docs/field#image
   */;
  logo: prismic.ImageField<never>;

  /**
   * business name field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.businessName
   * - **Tab**: seo
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  businessName: prismic.KeyTextField;

  /**
   * business description field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.businessDescription
   * - **Tab**: seo
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  businessDescription: prismic.KeyTextField;

  /**
   * business telephone field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.businessTelephone
   * - **Tab**: seo
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  businessTelephone: prismic.KeyTextField;

  /**
   * business email field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.businessEmail
   * - **Tab**: seo
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  businessEmail: prismic.KeyTextField;

  /**
   * street address field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.streetAddress
   * - **Tab**: seo
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  streetAddress: prismic.KeyTextField;

  /**
   * address locality field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.addressLocality
   * - **Tab**: seo
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  addressLocality: prismic.KeyTextField;

  /**
   * address region field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.addressRegion
   * - **Tab**: seo
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  addressRegion: prismic.KeyTextField;

  /**
   * postalcode field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.postalCode
   * - **Tab**: seo
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  postalCode: prismic.KeyTextField;

  /**
   * address country field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.addressCountry
   * - **Tab**: seo
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  addressCountry: prismic.KeyTextField;

  /**
   * images field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.images[]
   * - **Tab**: seo
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  images: prismic.GroupField<Simplify<SettingsDocumentDataImagesItem>>;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

export type AllDocumentTypes =
  | FlexiblePageDocument
  | GlobalSectionsDocument
  | LandingPageDocument
  | ServiceDocument
  | SettingsDocument;

/**
 * Primary content in *AboutHeadingBodytext → Primary*
 */
export interface AboutHeadingBodytextSliceDefaultPrimary {
  /**
   * heading field in *AboutHeadingBodytext → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_heading_bodytext.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * body text field in *AboutHeadingBodytext → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_heading_bodytext.primary.bodyText
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  bodyText: prismic.RichTextField;

  /**
   * button text field in *AboutHeadingBodytext → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_heading_bodytext.primary.buttonText
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  buttonText: prismic.KeyTextField;

  /**
   * button link field in *AboutHeadingBodytext → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: about_heading_bodytext.primary.buttonLink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  buttonLink: prismic.LinkField;
}

/**
 * Default variation for AboutHeadingBodytext Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutHeadingBodytextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AboutHeadingBodytextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *AboutHeadingBodytext*
 */
type AboutHeadingBodytextSliceVariation = AboutHeadingBodytextSliceDefault;

/**
 * AboutHeadingBodytext Shared Slice
 *
 * - **API ID**: `about_heading_bodytext`
 * - **Description**: AboutHeadingBodytext
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutHeadingBodytextSlice = prismic.SharedSlice<
  "about_heading_bodytext",
  AboutHeadingBodytextSliceVariation
>;

/**
 * Primary content in *AboutImage → Primary*
 */
export interface AboutImageSliceDefaultPrimary {
  /**
   * heading field in *AboutImage → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_image.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * body text field in *AboutImage → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_image.primary.bodyText
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  bodyText: prismic.RichTextField;

  /**
   * button text field in *AboutImage → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_image.primary.buttonText
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  buttonText: prismic.KeyTextField;

  /**
   * button link field in *AboutImage → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: about_image.primary.buttonLink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  buttonLink: prismic.LinkField;

  /**
   * image field in *AboutImage → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about_image.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for AboutImage Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutImageSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AboutImageSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *AboutImage → Primary*
 */
export interface AboutImageSliceWithStatsPrimary {
  /**
   * heading field in *AboutImage → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_image.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * body text field in *AboutImage → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_image.primary.bodyText
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  bodyText: prismic.RichTextField;

  /**
   * button text field in *AboutImage → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_image.primary.buttonText
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  buttonText: prismic.KeyTextField;

  /**
   * button link field in *AboutImage → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: about_image.primary.buttonLink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  buttonLink: prismic.LinkField;

  /**
   * image field in *AboutImage → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about_image.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * image caption field in *AboutImage → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_image.primary.imageCaption
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  imageCaption: prismic.RichTextField;

  /**
   * stats caption field in *AboutImage → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_image.primary.statsCaption
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  statsCaption: prismic.KeyTextField;

  /**
   * stats number field in *AboutImage → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: about_image.primary.statsNumber
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  statsNumber: prismic.NumberField;

  /**
   * stats unit field in *AboutImage → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_image.primary.statsUnit
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  statsUnit: prismic.KeyTextField;
}

/**
 * With Stats variation for AboutImage Slice
 *
 * - **API ID**: `withStats`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutImageSliceWithStats = prismic.SharedSliceVariation<
  "withStats",
  Simplify<AboutImageSliceWithStatsPrimary>,
  never
>;

/**
 * Slice variation for *AboutImage*
 */
type AboutImageSliceVariation =
  | AboutImageSliceDefault
  | AboutImageSliceWithStats;

/**
 * AboutImage Shared Slice
 *
 * - **API ID**: `about_image`
 * - **Description**: AboutImage
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutImageSlice = prismic.SharedSlice<
  "about_image",
  AboutImageSliceVariation
>;

/**
 * Primary content in *Advantage → Primary*
 */
export interface AdvantageSliceDefaultPrimary {
  /**
   * heading field in *Advantage → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: advantage.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * button text field in *Advantage → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: advantage.primary.buttonText
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  buttonText: prismic.KeyTextField;

  /**
   * button link field in *Advantage → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: advantage.primary.buttonLink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  buttonLink: prismic.LinkField;
}

/**
 * Primary content in *Advantage → Items*
 */
export interface AdvantageSliceDefaultItem {
  /**
   * advantage heading field in *Advantage → Items*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: advantage.items[].advantageHeading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  advantageHeading: prismic.TitleField;

  /**
   * advantage description field in *Advantage → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: advantage.items[].advantageDescription
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  advantageDescription: prismic.RichTextField;
}

/**
 * Default variation for Advantage Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AdvantageSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AdvantageSliceDefaultPrimary>,
  Simplify<AdvantageSliceDefaultItem>
>;

/**
 * Slice variation for *Advantage*
 */
type AdvantageSliceVariation = AdvantageSliceDefault;

/**
 * Advantage Shared Slice
 *
 * - **API ID**: `advantage`
 * - **Description**: Advantage
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AdvantageSlice = prismic.SharedSlice<
  "advantage",
  AdvantageSliceVariation
>;

/**
 * Primary content in *Benefits → Primary*
 */
export interface BenefitsSliceDefaultPrimary {
  /**
   * heading field in *Benefits → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: benefits.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * button text field in *Benefits → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: benefits.primary.buttonText
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  buttonText: prismic.KeyTextField;

  /**
   * button link field in *Benefits → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: benefits.primary.buttonLink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  buttonLink: prismic.LinkField;
}

/**
 * Primary content in *Benefits → Items*
 */
export interface BenefitsSliceDefaultItem {
  /**
   * benefit heading field in *Benefits → Items*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: benefits.items[].benefitHeading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  benefitHeading: prismic.TitleField;

  /**
   * benefitDescription field in *Benefits → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: benefits.items[].benefitdescription
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  benefitdescription: prismic.RichTextField;
}

/**
 * Default variation for Benefits Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BenefitsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BenefitsSliceDefaultPrimary>,
  Simplify<BenefitsSliceDefaultItem>
>;

/**
 * Slice variation for *Benefits*
 */
type BenefitsSliceVariation = BenefitsSliceDefault;

/**
 * Benefits Shared Slice
 *
 * - **API ID**: `benefits`
 * - **Description**: Benefits
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BenefitsSlice = prismic.SharedSlice<
  "benefits",
  BenefitsSliceVariation
>;

/**
 * Primary content in *ContactInfo → Primary*
 */
export interface ContactInfoSliceDefaultPrimary {
  /**
   * heading field in *ContactInfo → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_info.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * form heading field in *ContactInfo → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_info.primary.formHeading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  formHeading: prismic.RichTextField;
}

/**
 * Primary content in *ContactInfo → Items*
 */
export interface ContactInfoSliceDefaultItem {
  /**
   * heading field in *ContactInfo → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_info.items[].heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * text field in *ContactInfo → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_info.items[].text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text: prismic.KeyTextField;

  /**
   * link field in *ContactInfo → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_info.items[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Default variation for ContactInfo Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactInfoSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContactInfoSliceDefaultPrimary>,
  Simplify<ContactInfoSliceDefaultItem>
>;

/**
 * Slice variation for *ContactInfo*
 */
type ContactInfoSliceVariation = ContactInfoSliceDefault;

/**
 * ContactInfo Shared Slice
 *
 * - **API ID**: `contact_info`
 * - **Description**: ContactInfo
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactInfoSlice = prismic.SharedSlice<
  "contact_info",
  ContactInfoSliceVariation
>;

/**
 * Primary content in *Cta → Primary*
 */
export interface CtaSliceDefaultPrimary {
  /**
   * pre heading field in *Cta → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.primary.preHeading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  preHeading: prismic.RichTextField;

  /**
   * heading field in *Cta → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * body text field in *Cta → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.primary.bodyText
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  bodyText: prismic.RichTextField;

  /**
   * button text field in *Cta → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.primary.buttonText
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  buttonText: prismic.KeyTextField;

  /**
   * button link field in *Cta → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.primary.buttonLink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  buttonLink: prismic.LinkField;
}

/**
 * Default variation for Cta Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CtaSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CtaSliceDefaultPrimary>,
  never
>;

/**
 * Global Cta variation for Cta Slice
 *
 * - **API ID**: `globalCta`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CtaSliceGlobalCta = prismic.SharedSliceVariation<
  "globalCta",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *Cta*
 */
type CtaSliceVariation = CtaSliceDefault | CtaSliceGlobalCta;

/**
 * Cta Shared Slice
 *
 * - **API ID**: `cta`
 * - **Description**: Cta
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CtaSlice = prismic.SharedSlice<"cta", CtaSliceVariation>;

/**
 * Primary content in *CtaContact → Primary*
 */
export interface CtaContactSliceDefaultPrimary {
  /**
   * heading field in *CtaContact → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_contact.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * body text field in *CtaContact → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_contact.primary.bodyText
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  bodyText: prismic.RichTextField;
}

/**
 * Default variation for CtaContact Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CtaContactSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CtaContactSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CtaContact*
 */
type CtaContactSliceVariation = CtaContactSliceDefault;

/**
 * CtaContact Shared Slice
 *
 * - **API ID**: `cta_contact`
 * - **Description**: CtaContact
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CtaContactSlice = prismic.SharedSlice<
  "cta_contact",
  CtaContactSliceVariation
>;

/**
 * Primary content in *CtaGuarantee → Primary*
 */
export interface CtaGuaranteeSliceDefaultPrimary {
  /**
   * heading field in *CtaGuarantee → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_guarantee.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * body text field in *CtaGuarantee → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_guarantee.primary.bodyText
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  bodyText: prismic.RichTextField;

  /**
   * button text field in *CtaGuarantee → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_guarantee.primary.buttonText
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  buttonText: prismic.KeyTextField;

  /**
   * button link field in *CtaGuarantee → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_guarantee.primary.buttonLink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  buttonLink: prismic.LinkField;

  /**
   * guarantee image field in *CtaGuarantee → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_guarantee.primary.guaranteeImage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  guaranteeImage: prismic.ImageField<never>;
}

/**
 * Default variation for CtaGuarantee Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CtaGuaranteeSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CtaGuaranteeSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CtaGuarantee*
 */
type CtaGuaranteeSliceVariation = CtaGuaranteeSliceDefault;

/**
 * CtaGuarantee Shared Slice
 *
 * - **API ID**: `cta_guarantee`
 * - **Description**: CtaGuarantee
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CtaGuaranteeSlice = prismic.SharedSlice<
  "cta_guarantee",
  CtaGuaranteeSliceVariation
>;

/**
 * Primary content in *Faq → Primary*
 */
export interface FaqSliceDefaultPrimary {
  /**
   * heading field in *Faq → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;
}

/**
 * Primary content in *Faq → Items*
 */
export interface FaqSliceDefaultItem {
  /**
   * question field in *Faq → Items*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.items[].question
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  question: prismic.TitleField;

  /**
   * answer field in *Faq → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.items[].answer
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  answer: prismic.RichTextField;
}

/**
 * Default variation for Faq Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FaqSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FaqSliceDefaultPrimary>,
  Simplify<FaqSliceDefaultItem>
>;

/**
 * Slice variation for *Faq*
 */
type FaqSliceVariation = FaqSliceDefault;

/**
 * Faq Shared Slice
 *
 * - **API ID**: `faq`
 * - **Description**: Faq
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FaqSlice = prismic.SharedSlice<"faq", FaqSliceVariation>;

/**
 * Primary content in *FeaturedLists → Items*
 */
export interface FeaturedListsSliceDefaultItem {
  /**
   * heading field in *FeaturedLists → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_lists.items[].heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * description field in *FeaturedLists → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_lists.items[].description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;
}

/**
 * Default variation for FeaturedLists Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturedListsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<FeaturedListsSliceDefaultItem>
>;

/**
 * Slice variation for *FeaturedLists*
 */
type FeaturedListsSliceVariation = FeaturedListsSliceDefault;

/**
 * FeaturedLists Shared Slice
 *
 * - **API ID**: `featured_lists`
 * - **Description**: FeaturedLists
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturedListsSlice = prismic.SharedSlice<
  "featured_lists",
  FeaturedListsSliceVariation
>;

/**
 * Primary content in *FeaturedServices → Primary*
 */
export interface FeaturedServicesSliceDefaultPrimary {
  /**
   * heading field in *FeaturedServices → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_services.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;
}

/**
 * Primary content in *FeaturedServices → Items*
 */
export interface FeaturedServicesSliceDefaultItem {
  /**
   * service field in *FeaturedServices → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_services.items[].service
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  service: prismic.ContentRelationshipField<"service">;
}

/**
 * Default variation for FeaturedServices Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturedServicesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FeaturedServicesSliceDefaultPrimary>,
  Simplify<FeaturedServicesSliceDefaultItem>
>;

/**
 * Slice variation for *FeaturedServices*
 */
type FeaturedServicesSliceVariation = FeaturedServicesSliceDefault;

/**
 * FeaturedServices Shared Slice
 *
 * - **API ID**: `featured_services`
 * - **Description**: FeaturedServices
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturedServicesSlice = prismic.SharedSlice<
  "featured_services",
  FeaturedServicesSliceVariation
>;

/**
 * Primary content in *FooterNavigationItem → Primary*
 */
export interface FooterNavigationItemSliceDefaultPrimary {
  /**
   * group name field in *FooterNavigationItem → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_navigation_item.primary.group_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  group_name: prismic.KeyTextField;
}

/**
 * Primary content in *FooterNavigationItem → Items*
 */
export interface FooterNavigationItemSliceDefaultItem {
  /**
   * menu text field in *FooterNavigationItem → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_navigation_item.items[].menuText
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  menuText: prismic.RichTextField;

  /**
   * menu link field in *FooterNavigationItem → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_navigation_item.items[].menuLink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  menuLink: prismic.LinkField;
}

/**
 * Default variation for FooterNavigationItem Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FooterNavigationItemSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FooterNavigationItemSliceDefaultPrimary>,
  Simplify<FooterNavigationItemSliceDefaultItem>
>;

/**
 * Slice variation for *FooterNavigationItem*
 */
type FooterNavigationItemSliceVariation = FooterNavigationItemSliceDefault;

/**
 * FooterNavigationItem Shared Slice
 *
 * - **API ID**: `footer_navigation_item`
 * - **Description**: FooterNavigationItem
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FooterNavigationItemSlice = prismic.SharedSlice<
  "footer_navigation_item",
  FooterNavigationItemSliceVariation
>;

/**
 * Primary content in *Hero → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * image field in *Hero → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *LpHero → Primary*
 */
export interface LpHeroSliceDefaultPrimary {
  /**
   * overline field in *LpHero → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: lp_hero.primary.overline
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  overline: prismic.TitleField;

  /**
   * heading field in *LpHero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: lp_hero.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * body text field in *LpHero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: lp_hero.primary.bodyText
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  bodyText: prismic.RichTextField;

  /**
   * button text field in *LpHero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: lp_hero.primary.buttonText
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  buttonText: prismic.KeyTextField;

  /**
   * button link field in *LpHero → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: lp_hero.primary.buttonLink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  buttonLink: prismic.LinkField;

  /**
   * background image field in *LpHero → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: lp_hero.primary.backgroundImage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  backgroundImage: prismic.ImageField<never>;
}

/**
 * Primary content in *LpHero → Items*
 */
export interface LpHeroSliceDefaultItem {
  /**
   * stats number field in *LpHero → Items*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: lp_hero.items[].statsNumber
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  statsNumber: prismic.NumberField;

  /**
   * stats unit field in *LpHero → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: lp_hero.items[].statsUnit
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  statsUnit: prismic.KeyTextField;

  /**
   * stats caption field in *LpHero → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: lp_hero.items[].statsCaption
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  statsCaption: prismic.KeyTextField;
}

/**
 * Default variation for LpHero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LpHeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<LpHeroSliceDefaultPrimary>,
  Simplify<LpHeroSliceDefaultItem>
>;

/**
 * Slice variation for *LpHero*
 */
type LpHeroSliceVariation = LpHeroSliceDefault;

/**
 * LpHero Shared Slice
 *
 * - **API ID**: `lp_hero`
 * - **Description**: LpHero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LpHeroSlice = prismic.SharedSlice<"lp_hero", LpHeroSliceVariation>;

/**
 * Primary content in *NavigationItem → Primary*
 */
export interface NavigationItemSliceDefaultPrimary {
  /**
   * name field in *NavigationItem → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation_item.primary.name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * link field in *NavigationItem → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation_item.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * as button field in *NavigationItem → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: navigation_item.primary.asButton
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  asButton: prismic.BooleanField;
}

/**
 * Primary content in *NavigationItem → Items*
 */
export interface NavigationItemSliceDefaultItem {
  /**
   * child name field in *NavigationItem → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation_item.items[].childName
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  childName: prismic.KeyTextField;

  /**
   * child link field in *NavigationItem → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation_item.items[].childLink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  childLink: prismic.LinkField;
}

/**
 * Default variation for NavigationItem Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NavigationItemSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<NavigationItemSliceDefaultPrimary>,
  Simplify<NavigationItemSliceDefaultItem>
>;

/**
 * Slice variation for *NavigationItem*
 */
type NavigationItemSliceVariation = NavigationItemSliceDefault;

/**
 * NavigationItem Shared Slice
 *
 * - **API ID**: `navigation_item`
 * - **Description**: NavigationItem
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NavigationItemSlice = prismic.SharedSlice<
  "navigation_item",
  NavigationItemSliceVariation
>;

/**
 * Primary content in *Quote → Primary*
 */
export interface QuoteSliceDefaultPrimary {
  /**
   * heading field in *Quote → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: quote.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;
}

/**
 * Default variation for Quote Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type QuoteSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<QuoteSliceDefaultPrimary>,
  never
>;

/**
 * Global Quote variation for Quote Slice
 *
 * - **API ID**: `globalQuote`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type QuoteSliceGlobalQuote = prismic.SharedSliceVariation<
  "globalQuote",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *Quote*
 */
type QuoteSliceVariation = QuoteSliceDefault | QuoteSliceGlobalQuote;

/**
 * Quote Shared Slice
 *
 * - **API ID**: `quote`
 * - **Description**: Quote
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type QuoteSlice = prismic.SharedSlice<"quote", QuoteSliceVariation>;

/**
 * Primary content in *ServiceHeader → Primary*
 */
export interface ServiceHeaderSliceDefaultPrimary {
  /**
   * heading field in *ServiceHeader → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: service_header.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField;

  /**
   * body text field in *ServiceHeader → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_header.primary.bodyText
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  bodyText: prismic.RichTextField;

  /**
   * stats number field in *ServiceHeader → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: service_header.primary.statsNumber
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  statsNumber: prismic.NumberField;

  /**
   * stats unit field in *ServiceHeader → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_header.primary.statsUnit
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  statsUnit: prismic.KeyTextField;

  /**
   * stats caption field in *ServiceHeader → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_header.primary.statsCaption
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  statsCaption: prismic.KeyTextField;
}

/**
 * Primary content in *ServiceHeader → Items*
 */
export interface ServiceHeaderSliceDefaultItem {
  /**
   * lawyer field in *ServiceHeader → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: service_header.items[].lawyer
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  lawyer: prismic.ImageField<never>;
}

/**
 * Default variation for ServiceHeader Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServiceHeaderSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ServiceHeaderSliceDefaultPrimary>,
  Simplify<ServiceHeaderSliceDefaultItem>
>;

/**
 * Slice variation for *ServiceHeader*
 */
type ServiceHeaderSliceVariation = ServiceHeaderSliceDefault;

/**
 * ServiceHeader Shared Slice
 *
 * - **API ID**: `service_header`
 * - **Description**: ServiceHeader
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServiceHeaderSlice = prismic.SharedSlice<
  "service_header",
  ServiceHeaderSliceVariation
>;

/**
 * Primary content in *ServicesLists → Primary*
 */
export interface ServicesListsSliceDefaultPrimary {
  /**
   * heading field in *ServicesLists → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: services_lists.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField;
}

/**
 * Primary content in *ServicesLists → Items*
 */
export interface ServicesListsSliceDefaultItem {
  /**
   * service field in *ServicesLists → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: services_lists.items[].service
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  service: prismic.ContentRelationshipField<"service">;
}

/**
 * Default variation for ServicesLists Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServicesListsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ServicesListsSliceDefaultPrimary>,
  Simplify<ServicesListsSliceDefaultItem>
>;

/**
 * Slice variation for *ServicesLists*
 */
type ServicesListsSliceVariation = ServicesListsSliceDefault;

/**
 * ServicesLists Shared Slice
 *
 * - **API ID**: `services_lists`
 * - **Description**: ServicesLists
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServicesListsSlice = prismic.SharedSlice<
  "services_lists",
  ServicesListsSliceVariation
>;

/**
 * Default variation for SimpleTextField Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SimpleTextFieldSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *SimpleTextField*
 */
type SimpleTextFieldSliceVariation = SimpleTextFieldSliceDefault;

/**
 * SimpleTextField Shared Slice
 *
 * - **API ID**: `simple_text_field`
 * - **Description**: SimpleTextField
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SimpleTextFieldSlice = prismic.SharedSlice<
  "simple_text_field",
  SimpleTextFieldSliceVariation
>;

/**
 * Primary content in *Steps → Primary*
 */
export interface StepsSliceDefaultPrimary {
  /**
   * heading field in *Steps → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: steps.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;
}

/**
 * Primary content in *Steps → Items*
 */
export interface StepsSliceDefaultItem {
  /**
   * step heading field in *Steps → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: steps.items[].stepHeading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  stepHeading: prismic.KeyTextField;

  /**
   * step description field in *Steps → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: steps.items[].stepDescription
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  stepDescription: prismic.KeyTextField;
}

/**
 * Default variation for Steps Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StepsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<StepsSliceDefaultPrimary>,
  Simplify<StepsSliceDefaultItem>
>;

/**
 * Step Global variation for Steps Slice
 *
 * - **API ID**: `stepGlobal`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StepsSliceStepGlobal = prismic.SharedSliceVariation<
  "stepGlobal",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *Steps*
 */
type StepsSliceVariation = StepsSliceDefault | StepsSliceStepGlobal;

/**
 * Steps Shared Slice
 *
 * - **API ID**: `steps`
 * - **Description**: Steps
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StepsSlice = prismic.SharedSlice<"steps", StepsSliceVariation>;

/**
 * Primary content in *Subservices → Primary*
 */
export interface SubservicesSliceDefaultPrimary {
  /**
   * heading field in *Subservices → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: subservices.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * button text field in *Subservices → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: subservices.primary.buttonText
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  buttonText: prismic.KeyTextField;

  /**
   * button link field in *Subservices → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: subservices.primary.buttonLink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  buttonLink: prismic.LinkField;
}

/**
 * Primary content in *Subservices → Items*
 */
export interface SubservicesSliceDefaultItem {
  /**
   * heading field in *Subservices → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: subservices.items[].heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * description field in *Subservices → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: subservices.items[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Default variation for Subservices Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SubservicesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SubservicesSliceDefaultPrimary>,
  Simplify<SubservicesSliceDefaultItem>
>;

/**
 * Slice variation for *Subservices*
 */
type SubservicesSliceVariation = SubservicesSliceDefault;

/**
 * Subservices Shared Slice
 *
 * - **API ID**: `subservices`
 * - **Description**: Subservices
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SubservicesSlice = prismic.SharedSlice<
  "subservices",
  SubservicesSliceVariation
>;

/**
 * Primary content in *TeamLists → Primary*
 */
export interface TeamListsSliceDefaultPrimary {
  /**
   * heading field in *TeamLists → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team_lists.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;
}

/**
 * Primary content in *TeamLists → Items*
 */
export interface TeamListsSliceDefaultItem {
  /**
   * name field in *TeamLists → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team_lists.items[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * title field in *TeamLists → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team_lists.items[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * email field in *TeamLists → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team_lists.items[].email
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  email: prismic.KeyTextField;
}

/**
 * Default variation for TeamLists Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TeamListsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TeamListsSliceDefaultPrimary>,
  Simplify<TeamListsSliceDefaultItem>
>;

/**
 * Slice variation for *TeamLists*
 */
type TeamListsSliceVariation = TeamListsSliceDefault;

/**
 * TeamLists Shared Slice
 *
 * - **API ID**: `team_lists`
 * - **Description**: TeamLists
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TeamListsSlice = prismic.SharedSlice<
  "team_lists",
  TeamListsSliceVariation
>;

/**
 * Primary content in *TeamPartners → Primary*
 */
export interface TeamPartnersSliceDefaultPrimary {
  /**
   * heading field in *TeamPartners → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team_partners.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;
}

/**
 * Primary content in *TeamPartners → Items*
 */
export interface TeamPartnersSliceDefaultItem {
  /**
   * image field in *TeamPartners → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: team_partners.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * name field in *TeamPartners → Items*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: team_partners.items[].name
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  name: prismic.TitleField;

  /**
   * description field in *TeamPartners → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team_partners.items[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * position field in *TeamPartners → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team_partners.items[].position
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  position: prismic.KeyTextField;

  /**
   * email field in *TeamPartners → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team_partners.items[].email
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  email: prismic.KeyTextField;

  /**
   * phone field in *TeamPartners → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team_partners.items[].phone
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  phone: prismic.KeyTextField;
}

/**
 * Default variation for TeamPartners Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TeamPartnersSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TeamPartnersSliceDefaultPrimary>,
  Simplify<TeamPartnersSliceDefaultItem>
>;

/**
 * Slice variation for *TeamPartners*
 */
type TeamPartnersSliceVariation = TeamPartnersSliceDefault;

/**
 * TeamPartners Shared Slice
 *
 * - **API ID**: `team_partners`
 * - **Description**: TeamPartners
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TeamPartnersSlice = prismic.SharedSlice<
  "team_partners",
  TeamPartnersSliceVariation
>;

/**
 * Primary content in *WysiwygTextBlock → Primary*
 */
export interface WysiwygTextBlockSliceDefaultPrimary {
  /**
   * text block field in *WysiwygTextBlock → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: wysiwyg_text_block.primary.textBlock
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  textBlock: prismic.RichTextField;
}

/**
 * Default variation for WysiwygTextBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WysiwygTextBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<WysiwygTextBlockSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *WysiwygTextBlock*
 */
type WysiwygTextBlockSliceVariation = WysiwygTextBlockSliceDefault;

/**
 * WysiwygTextBlock Shared Slice
 *
 * - **API ID**: `wysiwyg_text_block`
 * - **Description**: WysiwygTextBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WysiwygTextBlockSlice = prismic.SharedSlice<
  "wysiwyg_text_block",
  WysiwygTextBlockSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      FlexiblePageDocument,
      FlexiblePageDocumentData,
      FlexiblePageDocumentDataSlicesSlice,
      GlobalSectionsDocument,
      GlobalSectionsDocumentData,
      GlobalSectionsDocumentDataStepItemsItem,
      LandingPageDocument,
      LandingPageDocumentData,
      LandingPageDocumentDataSlicesSlice,
      ServiceDocument,
      ServiceDocumentData,
      ServiceDocumentDataSlicesSlice,
      SettingsDocument,
      SettingsDocumentData,
      SettingsDocumentDataSlicesSlice,
      SettingsDocumentDataSlices1Slice,
      SettingsDocumentDataSocialItem,
      SettingsDocumentDataImagesItem,
      AllDocumentTypes,
      AboutHeadingBodytextSlice,
      AboutHeadingBodytextSliceDefaultPrimary,
      AboutHeadingBodytextSliceVariation,
      AboutHeadingBodytextSliceDefault,
      AboutImageSlice,
      AboutImageSliceDefaultPrimary,
      AboutImageSliceWithStatsPrimary,
      AboutImageSliceVariation,
      AboutImageSliceDefault,
      AboutImageSliceWithStats,
      AdvantageSlice,
      AdvantageSliceDefaultPrimary,
      AdvantageSliceDefaultItem,
      AdvantageSliceVariation,
      AdvantageSliceDefault,
      BenefitsSlice,
      BenefitsSliceDefaultPrimary,
      BenefitsSliceDefaultItem,
      BenefitsSliceVariation,
      BenefitsSliceDefault,
      ContactInfoSlice,
      ContactInfoSliceDefaultPrimary,
      ContactInfoSliceDefaultItem,
      ContactInfoSliceVariation,
      ContactInfoSliceDefault,
      CtaSlice,
      CtaSliceDefaultPrimary,
      CtaSliceVariation,
      CtaSliceDefault,
      CtaSliceGlobalCta,
      CtaContactSlice,
      CtaContactSliceDefaultPrimary,
      CtaContactSliceVariation,
      CtaContactSliceDefault,
      CtaGuaranteeSlice,
      CtaGuaranteeSliceDefaultPrimary,
      CtaGuaranteeSliceVariation,
      CtaGuaranteeSliceDefault,
      FaqSlice,
      FaqSliceDefaultPrimary,
      FaqSliceDefaultItem,
      FaqSliceVariation,
      FaqSliceDefault,
      FeaturedListsSlice,
      FeaturedListsSliceDefaultItem,
      FeaturedListsSliceVariation,
      FeaturedListsSliceDefault,
      FeaturedServicesSlice,
      FeaturedServicesSliceDefaultPrimary,
      FeaturedServicesSliceDefaultItem,
      FeaturedServicesSliceVariation,
      FeaturedServicesSliceDefault,
      FooterNavigationItemSlice,
      FooterNavigationItemSliceDefaultPrimary,
      FooterNavigationItemSliceDefaultItem,
      FooterNavigationItemSliceVariation,
      FooterNavigationItemSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      LpHeroSlice,
      LpHeroSliceDefaultPrimary,
      LpHeroSliceDefaultItem,
      LpHeroSliceVariation,
      LpHeroSliceDefault,
      NavigationItemSlice,
      NavigationItemSliceDefaultPrimary,
      NavigationItemSliceDefaultItem,
      NavigationItemSliceVariation,
      NavigationItemSliceDefault,
      QuoteSlice,
      QuoteSliceDefaultPrimary,
      QuoteSliceVariation,
      QuoteSliceDefault,
      QuoteSliceGlobalQuote,
      ServiceHeaderSlice,
      ServiceHeaderSliceDefaultPrimary,
      ServiceHeaderSliceDefaultItem,
      ServiceHeaderSliceVariation,
      ServiceHeaderSliceDefault,
      ServicesListsSlice,
      ServicesListsSliceDefaultPrimary,
      ServicesListsSliceDefaultItem,
      ServicesListsSliceVariation,
      ServicesListsSliceDefault,
      SimpleTextFieldSlice,
      SimpleTextFieldSliceVariation,
      SimpleTextFieldSliceDefault,
      StepsSlice,
      StepsSliceDefaultPrimary,
      StepsSliceDefaultItem,
      StepsSliceVariation,
      StepsSliceDefault,
      StepsSliceStepGlobal,
      SubservicesSlice,
      SubservicesSliceDefaultPrimary,
      SubservicesSliceDefaultItem,
      SubservicesSliceVariation,
      SubservicesSliceDefault,
      TeamListsSlice,
      TeamListsSliceDefaultPrimary,
      TeamListsSliceDefaultItem,
      TeamListsSliceVariation,
      TeamListsSliceDefault,
      TeamPartnersSlice,
      TeamPartnersSliceDefaultPrimary,
      TeamPartnersSliceDefaultItem,
      TeamPartnersSliceVariation,
      TeamPartnersSliceDefault,
      WysiwygTextBlockSlice,
      WysiwygTextBlockSliceDefaultPrimary,
      WysiwygTextBlockSliceVariation,
      WysiwygTextBlockSliceDefault,
    };
  }
}
