// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about_heading_bodytext: dynamic(() => import("./AboutHeadingBodytext")),
  about_image: dynamic(() => import("./AboutImage")),
  advantage: dynamic(() => import("./Advantage")),
  benefits: dynamic(() => import("./Benefits")),
  contact_info: dynamic(() => import("./ContactInfo")),
  cta: dynamic(() => import("./Cta")),
  cta_contact: dynamic(() => import("./CtaContact")),
  cta_guarantee: dynamic(() => import("./CtaGuarantee")),
  faq: dynamic(() => import("./Faq")),
  featured_lists: dynamic(() => import("./FeaturedLists")),
  featured_services: dynamic(() => import("./FeaturedServices")),
  footer_navigation_item: dynamic(() => import("./FooterNavigationItem")),
  hero: dynamic(() => import("./Hero")),
  lp_hero: dynamic(() => import("./LpHero")),
  navigation_item: dynamic(() => import("./NavigationItem")),
  quote: dynamic(() => import("./Quote")),
  service_header: dynamic(() => import("./ServiceHeader")),
  services_lists: dynamic(() => import("./ServicesLists")),
  simple_text_field: dynamic(() => import("./SimpleTextField")),
  steps: dynamic(() => import("./Steps")),
  subservices: dynamic(() => import("./Subservices")),
  team_lists: dynamic(() => import("./TeamLists")),
  team_partners: dynamic(() => import("./TeamPartners")),
  wysiwyg_text_block: dynamic(() => import("./WysiwygTextBlock")),
};
